/**
 * Aura Laundry Platform — Notification Event Constants Registry
 */
export const NOTIFICATION_EVENTS = {
  // Admin Notifications
  ADMIN_PROVIDER_REGISTRATION_PENDING: 'ADMIN_PROVIDER_REGISTRATION_PENDING',
  ADMIN_PROVIDER_COMMISSION_REQUESTED: 'ADMIN_PROVIDER_COMMISSION_REQUESTED',
  ADMIN_MALICIOUS_ACTIVITY_DETECTED: 'ADMIN_MALICIOUS_ACTIVITY_DETECTED',
  ADMIN_PROMOTION_APPROVAL_REQUESTED: 'ADMIN_PROMOTION_APPROVAL_REQUESTED',

  // Provider / Cleaner Notifications
  PROVIDER_ORDER_PAYMENT_CONFIRMED: 'PROVIDER_ORDER_PAYMENT_CONFIRMED',
  PROVIDER_PAID_ORDERS_UNREVIEWED: 'PROVIDER_PAID_ORDERS_UNREVIEWED',
  PROVIDER_RATING_UPDATED: 'PROVIDER_RATING_UPDATED',
  PROVIDER_PROMOTION_PAYMENT_RECEIPT: 'PROVIDER_PROMOTION_PAYMENT_RECEIPT',
  PROVIDER_PROMOTION_EXPIRY_30_DAYS: 'PROVIDER_PROMOTION_EXPIRY_30_DAYS',
  PROVIDER_PROMOTION_EXPIRY_14_DAYS: 'PROVIDER_PROMOTION_EXPIRY_14_DAYS',
  PROVIDER_PROMOTION_EXPIRY_7_DAYS: 'PROVIDER_PROMOTION_EXPIRY_7_DAYS',
  PROVIDER_PAYOUT_INVOICE_SENT: 'PROVIDER_PAYOUT_INVOICE_SENT',

  // Order & General Notifications (for future multi-channel expansion)
  ORDER_CONFIRMATION: 'ORDER_CONFIRMATION',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED'
};

export default NOTIFICATION_EVENTS;
