/**
 * Laundry Platform — Notification Event Constants Registry
 */
export const NOTIFICATION_EVENTS = {
  // Authentication & Security
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  OTP_REQUESTED: 'OTP_REQUESTED',
  PASSWORD_RESET: 'PASSWORD_RESET',

  // Customer Order Lifecycle Notifications (Multi-Channel: Email, SMS, In-App)
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_CONFIRMATION: 'ORDER_CONFIRMATION',
  ORDER_PICKUP_SCHEDULED: 'ORDER_PICKUP_SCHEDULED',
  ORDER_PICKED_UP: 'ORDER_PICKED_UP',
  ORDER_IN_WASH: 'ORDER_IN_WASH',
  ORDER_READY_FOR_DELIVERY: 'ORDER_READY_FOR_DELIVERY',
  ORDER_OUT_FOR_DELIVERY: 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',

  // Payment Notifications
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  // Admin Notifications
  ADMIN_NEW_ORDER_PLACED: 'ADMIN_NEW_ORDER_PLACED',
  ADMIN_PROVIDER_REGISTRATION_PENDING: 'ADMIN_PROVIDER_REGISTRATION_PENDING',
  ADMIN_PROVIDER_COMMISSION_REQUESTED: 'ADMIN_PROVIDER_COMMISSION_REQUESTED',
  ADMIN_MALICIOUS_ACTIVITY_DETECTED: 'ADMIN_MALICIOUS_ACTIVITY_DETECTED',
  ADMIN_PROMOTION_APPROVAL_REQUESTED: 'ADMIN_PROMOTION_APPROVAL_REQUESTED',

  // Provider / Cleaner Notifications
  PROVIDER_ORDER_ASSIGNED: 'PROVIDER_ORDER_ASSIGNED',
  PROVIDER_ORDER_PAYMENT_CONFIRMED: 'PROVIDER_ORDER_PAYMENT_CONFIRMED',
  PROVIDER_PAID_ORDERS_UNREVIEWED: 'PROVIDER_PAID_ORDERS_UNREVIEWED',
  PROVIDER_RATING_UPDATED: 'PROVIDER_RATING_UPDATED',
  PROVIDER_PROMOTION_PAYMENT_RECEIPT: 'PROVIDER_PROMOTION_PAYMENT_RECEIPT',
  PROVIDER_PROMOTION_EXPIRY_30_DAYS: 'PROVIDER_PROMOTION_EXPIRY_30_DAYS',
  PROVIDER_PROMOTION_EXPIRY_14_DAYS: 'PROVIDER_PROMOTION_EXPIRY_14_DAYS',
  PROVIDER_PROMOTION_EXPIRY_7_DAYS: 'PROVIDER_PROMOTION_EXPIRY_7_DAYS',
  PROVIDER_PAYOUT_INVOICE_SENT: 'PROVIDER_PAYOUT_INVOICE_SENT'
};

export default NOTIFICATION_EVENTS;
